### ISSUE TITLE
err

### ISSUE THREAD

**Issue by mr-zamir-op** [RevoltSecurities/GoogleDorker#10]
PS C:\Users\user pc\Downloads\GoogleDorker-1.0.1\GoogleDorker-1.0.1> dorker -q "site:***********.com inurl:admin"
     _               _
    | |             | |
  __| |  ___   _ __ | | __  ___  _ __
 / _` | / _ \ | '__|| |/ / / _ \| '__|
| (_| || (_) || |   |   < |  __/| |
 \__,_| \___/ |_|   |_|\_\ \___||_|

                    - RevoltSecurities

[version]: dorker current version v1.0.1 (latest)
[ERR]: Exception occured in the Keyreader module due to: Cannot choose from an empty sequence, <class 'IndexError'>
[ERR]: Exception occured in the google search request module due to: cannot unpack non-iterable NoneType object, <class 'TypeError'>
Dorker |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 1/1 [100%] in 0.0s (62.58/s)

**Comment by RevoltSecurities** [comment]
Hi @mr-zamir-op ,
Please setup your API keys and cxid in a proper format.

Kind regards,
@RevoltSecurities

**Comment by mr-zamir-op** [comment]
isn't it correct?
![Screenshot (4)](https://github.com/user-attachments/assets/c285a1e1-de20-41c5-abe0-ffe31395c6d5)

**Comment by mr-zamir-op** [comment]
oh i just did dorker -cp and it gave me a warn and i thought that now thats the default path for it but after i got error i edited the yaml on the default directory and then it did worked
