### ISSUE TITLE
api keys

### ISSUE THREAD

**Issue by MageScript** [RevoltSecurities/GoogleDorker#2]
are the google free api key locked for ever after 100 requests ?
or it unlocks itself every day ?

**Comment by RevoltSecurities** [comment]
Hey @El0rdihacks ,
According to google api docs each keys can be used for 100 requests per day so your keys usage will be reset again and  for more details u can check [here](https://developers.google.com/custom-search/v1/overview)

**Comment by MageScript** [comment]
thanks !
so theorically, we can get an unlimited amount of keys to use an unlimited amount of requests.
why would someone pay for custom research api ?

**Comment by RevoltSecurities** [comment]
@El0rdihacks ,
Hope you got it and there is also some companies are there intrested to pay for this service because when it's comes to org they require lot of requests for their key.

**Comment by MageScript** [comment]
If we pay , can we go further than the 100th result research ?
By the way I'd like to talk in private with you about what we can do with your program.
Can you pm me ? alt.hm-77myp7s@yopmail.com

**Comment by RevoltSecurities** [comment]
Hey @El0rdihacks ,
I don't know abt more than 100 results but you can refer the documentation of google. Yeah ofcourse I will text you and I request you if you're doubts are clear you can close this issue.
