### ISSUE TITLE
Not Running Correctly.

### ISSUE THREAD

**Issue by BuckLaFleur** [RevoltSecurities/GoogleDorker#5]
The tool isn't running correctly. The api keys are formatted correctly.
![Screenshot 2024-12-08 140917](https://github.com/user-attachments/assets/15a46305-9e7e-4ad3-99ad-6b690fd66725)

**Comment by RevoltSecurities** [comment]
Hey @BuckLaFleur ,
We request you to provide your yaml config screenshot with some redaction and try to proxy your request and monitory whether the request is going or not and also try to run dorker with `--verbose`  enabled, this helps you whats the real issue and providing these details will help to resolve your issue.

Kind regards,
@RevoltSecurities

**Comment by BuckLaFleur** [comment]
![POC1](https://github.com/user-attachments/assets/36e6ee00-c380-4a51-a2cc-0be533d8283d)
![POC2](https://github.com/user-attachments/assets/e0f8da8c-6508-4a2f-a883-8e27d7667232)
I believe there is no documentation on how to correctly format the http proxy/port. Here are some screenshots of the config file and running the tool with proxy and verbose flags

**Comment by RevoltSecurities** [comment]
Hi @BuckLaFleur ,
Looks like there is a issue in your API key configurations because  the `key1` & `key2`...n indicates the API key of the google not refers to key number so we request you change your keys configurations and here Im mention a sample a config below:

```yaml

google: [
    # goole-api-key:cxid format
    ASdshsb3u9gubo4ubADK:12hkv1h231vi1,
    Adsugorwgowrgugougwugbu:1279t9t492t9
    ]
```

**Comment by BuckLaFleur** [comment]
![perfect](https://github.com/user-attachments/assets/650aeb0b-1208-4787-9c3b-ad9677537c3c)
Works! Thank you!

**Comment by RevoltSecurities** [comment]
Hi @BuckLaFleur ,
Happy to hear that its working great and if you think your issue is solved then you can close this issue and support us by sharing our tools with others.

Kind regards,
@RevoltSecurities
